// This file is auto generated
// Use `npm run code-generate:images` to update this file
export type ImageAssets = Record<
  | 'autoBattleSwitchOff'
  | 'cancelButton'
  | 'closeButton'
  | 'cloverButton'
  | 'cloverPage'
  | 'continueButtonBlue'
  | 'continueButtonRed'
  | 'enemyLegend'
  | 'giveUpButtonBlue'
  | 'giveUpButtonWhite'
  | 'levelSelect'
  | 'levelSelectBeginner'
  | 'levelSelectExpert'
  | 'levelSelectMaster'
  | 'levelSelectStandard'
  | 'loadingText'
  | 'lv29Button'
  | 'menuButton'
  | 'nextText'
  | 'noRareItem1'
  | 'noRareItem2'
  | 'okButton'
  | 'presentButton'
  | 'presentPrice0'
  | 'presentPrice1500'
  | 'presentPrice15000'
  | 'presentPrice4000'
  | 'presentPrice8000'
  | 'rareItem'
  | 'repeatBattleButton'
  | 'repeatWithStaminaButton'
  | 'retryButtonBlue'
  | 'retryButtonRed'
  | 'startBattleButton'
  | 'supportSelectButton'
  | 'supportSkillAvailable'
  | 'tapButton'
  | 'transformGaugeFull',
  Image
>;
