version: '2.1'
executors:
  node:
    docker:
      - image: circleci/node:lts
  golang:
    docker:
      - image: circleci/golang:1.13
commands:
  install_hub:
    description: 'Install hub CLI'
    steps:
      - run:
          name: 'Install hub CLI'
          command: go get github.com/github/hub && hub --version
jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: 'Install dependencies'
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Code generation
          command: npm run code-generate:images
      - run:
          name: Build
          command: npm run build
      - run:
          name: Archive
          command: mkdir artifacts && python -m zipfile -c artifacts/auto-dragalia-${CIRCLE_TAG:-${CIRCLE_SHA1:0:8}}.zip dist/*
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: artifacts
          paths:
            - '*.zip'
      - run:
          name: 'Record CIRCLE_BUILD_URL'
          command: echo ${CIRCLE_BUILD_URL} > /tmp/CIRCLE_BUILD_URL
      - persist_to_workspace:
          root: /tmp
          paths:
            - 'CIRCLE_BUILD_URL'
  github-comment:
    executor: golang
    steps:
      - install_hub
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: 'Add github comment'
          command: export CIRCLE_BUILD_URL=`cat /tmp/workspace/CIRCLE_BUILD_URL`; .circleci/comment.sh
  github-release:
    executor: golang
    steps:
      - install_hub
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: 'Release'
          command: hub release create -d -m "${CIRCLE_TAG}" -a "/tmp/workspace/auto-dragalia-${CIRCLE_TAG}.zip" ${CIRCLE_TAG}
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - github-comment:
          requires:
            - build
      - github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.+/
            branches:
              ignore: /.*/
