// This file is auto generated
// Use `npm run code-generate:images` to update this file
import autoBattleSwitchOffPng from '@/assets/images/auto-battle-switch-off.png';
import closeButtonPng from '@/assets/images/close-button.png';
import continueButtonPng from '@/assets/images/continue-button.png';
import enemyLegendPng from '@/assets/images/enemy-legend.png';
import giveUpButtonBluePng from '@/assets/images/give-up-button-blue.png';
import giveUpButtonWhitePng from '@/assets/images/give-up-button-white.png';
import okButtonPng from '@/assets/images/ok-button.png';
import presentButtonPng from '@/assets/images/present-button.png';
import presentPrice0Png from '@/assets/images/present-price-0.png';
import presentPrice1500Png from '@/assets/images/present-price-1500.png';
import presentPrice15000Png from '@/assets/images/present-price-15000.png';
import presentPrice4000Png from '@/assets/images/present-price-4000.png';
import presentPrice8000Png from '@/assets/images/present-price-8000.png';
import repeatBattleButtonPng from '@/assets/images/repeat-battle-button.png';
import repeatWithStaminaButtonPng from '@/assets/images/repeat-with-stamina-button.png';
import retryButtonPng from '@/assets/images/retry-button.png';
import startBattleButtonPng from '@/assets/images/start-battle-button.png';
import supportSkillAvailablePng from '@/assets/images/support-skill-available.png';
import transformGaugeFullPng from '@/assets/images/transform-gauge-full.png';

export const autoBattleSwitchOff: Image = images.fromBase64(autoBattleSwitchOffPng);
export const closeButton: Image = images.fromBase64(closeButtonPng);
export const continueButton: Image = images.fromBase64(continueButtonPng);
export const enemyLegend: Image = images.fromBase64(enemyLegendPng);
export const giveUpButtonBlue: Image = images.fromBase64(giveUpButtonBluePng);
export const giveUpButtonWhite: Image = images.fromBase64(giveUpButtonWhitePng);
export const okButton: Image = images.fromBase64(okButtonPng);
export const presentButton: Image = images.fromBase64(presentButtonPng);
export const presentPrice0: Image = images.fromBase64(presentPrice0Png);
export const presentPrice1500: Image = images.fromBase64(presentPrice1500Png);
export const presentPrice15000: Image = images.fromBase64(presentPrice15000Png);
export const presentPrice4000: Image = images.fromBase64(presentPrice4000Png);
export const presentPrice8000: Image = images.fromBase64(presentPrice8000Png);
export const repeatBattleButton: Image = images.fromBase64(repeatBattleButtonPng);
export const repeatWithStaminaButton: Image = images.fromBase64(repeatWithStaminaButtonPng);
export const retryButton: Image = images.fromBase64(retryButtonPng);
export const startBattleButton: Image = images.fromBase64(startBattleButtonPng);
export const supportSkillAvailable: Image = images.fromBase64(supportSkillAvailablePng);
export const transformGaugeFull: Image = images.fromBase64(transformGaugeFullPng);
