// This file is auto generated
// Use `npm run code-generate:images` to update this file
import * as autoBattleSwitchOffPng from '@/assets/images/2160x1080/auto-battle-switch-off.png';
import * as cancelButtonPng from '@/assets/images/2160x1080/cancel-button.png';
import * as closeButtonPng from '@/assets/images/2160x1080/close-button.png';
import * as cloverButtonPng from '@/assets/images/2160x1080/clover-button.png';
import * as cloverPagePng from '@/assets/images/2160x1080/clover-page.png';
import * as continueButtonBluePng from '@/assets/images/2160x1080/continue-button-blue.png';
import * as continueButtonRedPng from '@/assets/images/2160x1080/continue-button-red.png';
import * as enemyLegendPng from '@/assets/images/2160x1080/enemy-legend.png';
import * as giveUpButtonBluePng from '@/assets/images/2160x1080/give-up-button-blue.png';
import * as giveUpButtonWhitePng from '@/assets/images/2160x1080/give-up-button-white.png';
import * as levelSelectBeginnerPng from '@/assets/images/2160x1080/level-select-beginner.png';
import * as levelSelectExpertPng from '@/assets/images/2160x1080/level-select-expert.png';
import * as levelSelectMasterPng from '@/assets/images/2160x1080/level-select-master.png';
import * as levelSelectStandardPng from '@/assets/images/2160x1080/level-select-standard.png';
import * as levelSelectPng from '@/assets/images/2160x1080/level-select.png';
import * as loadingTextPng from '@/assets/images/2160x1080/loading-text.png';
import * as lv29ButtonPng from '@/assets/images/2160x1080/lv29-button.png';
import * as menuButtonPng from '@/assets/images/2160x1080/menu-button.png';
import * as nextTextPng from '@/assets/images/2160x1080/next-text.png';
import * as noRareItem1Png from '@/assets/images/2160x1080/no-rare-item-1.png';
import * as noRareItem2Png from '@/assets/images/2160x1080/no-rare-item-2.png';
import * as noRareItem3Png from '@/assets/images/2160x1080/no-rare-item-3.png';
import * as noRareItem4Png from '@/assets/images/2160x1080/no-rare-item-4.png';
import * as okButtonPng from '@/assets/images/2160x1080/ok-button.png';
import * as presentButtonPng from '@/assets/images/2160x1080/present-button.png';
import * as presentPrice0Png from '@/assets/images/2160x1080/present-price-0.png';
import * as presentPrice1500Png from '@/assets/images/2160x1080/present-price-1500.png';
import * as presentPrice15000Png from '@/assets/images/2160x1080/present-price-15000.png';
import * as presentPrice4000Png from '@/assets/images/2160x1080/present-price-4000.png';
import * as presentPrice8000Png from '@/assets/images/2160x1080/present-price-8000.png';
import * as rareItem1Png from '@/assets/images/2160x1080/rare-item-1.png';
import * as rareItem2Png from '@/assets/images/2160x1080/rare-item-2.png';
import * as repeatBattleButtonPng from '@/assets/images/2160x1080/repeat-battle-button.png';
import * as repeatWithStaminaButtonPng from '@/assets/images/2160x1080/repeat-with-stamina-button.png';
import * as retryButtonBluePng from '@/assets/images/2160x1080/retry-button-blue.png';
import * as retryButtonRedPng from '@/assets/images/2160x1080/retry-button-red.png';
import * as startBattleButtonPng from '@/assets/images/2160x1080/start-battle-button.png';
import * as supportSelectButtonPng from '@/assets/images/2160x1080/support-select-button.png';
import * as supportSkillAvailablePng from '@/assets/images/2160x1080/support-skill-available.png';
import * as tapButtonPng from '@/assets/images/2160x1080/tap-button.png';
import * as transformGaugeFullPng from '@/assets/images/2160x1080/transform-gauge-full.png';

export const index: Record<string, Image> = {};

index.autoBattleSwitchOff = images.fromBase64(autoBattleSwitchOffPng);
index.cancelButton = images.fromBase64(cancelButtonPng);
index.closeButton = images.fromBase64(closeButtonPng);
index.cloverButton = images.fromBase64(cloverButtonPng);
index.cloverPage = images.fromBase64(cloverPagePng);
index.continueButtonBlue = images.fromBase64(continueButtonBluePng);
index.continueButtonRed = images.fromBase64(continueButtonRedPng);
index.enemyLegend = images.fromBase64(enemyLegendPng);
index.giveUpButtonBlue = images.fromBase64(giveUpButtonBluePng);
index.giveUpButtonWhite = images.fromBase64(giveUpButtonWhitePng);
index.levelSelectBeginner = images.fromBase64(levelSelectBeginnerPng);
index.levelSelectExpert = images.fromBase64(levelSelectExpertPng);
index.levelSelectMaster = images.fromBase64(levelSelectMasterPng);
index.levelSelectStandard = images.fromBase64(levelSelectStandardPng);
index.levelSelect = images.fromBase64(levelSelectPng);
index.loadingText = images.fromBase64(loadingTextPng);
index.lv29Button = images.fromBase64(lv29ButtonPng);
index.menuButton = images.fromBase64(menuButtonPng);
index.nextText = images.fromBase64(nextTextPng);
index.noRareItem1 = images.fromBase64(noRareItem1Png);
index.noRareItem2 = images.fromBase64(noRareItem2Png);
index.noRareItem3 = images.fromBase64(noRareItem3Png);
index.noRareItem4 = images.fromBase64(noRareItem4Png);
index.okButton = images.fromBase64(okButtonPng);
index.presentButton = images.fromBase64(presentButtonPng);
index.presentPrice0 = images.fromBase64(presentPrice0Png);
index.presentPrice1500 = images.fromBase64(presentPrice1500Png);
index.presentPrice15000 = images.fromBase64(presentPrice15000Png);
index.presentPrice4000 = images.fromBase64(presentPrice4000Png);
index.presentPrice8000 = images.fromBase64(presentPrice8000Png);
index.rareItem1 = images.fromBase64(rareItem1Png);
index.rareItem2 = images.fromBase64(rareItem2Png);
index.repeatBattleButton = images.fromBase64(repeatBattleButtonPng);
index.repeatWithStaminaButton = images.fromBase64(repeatWithStaminaButtonPng);
index.retryButtonBlue = images.fromBase64(retryButtonBluePng);
index.retryButtonRed = images.fromBase64(retryButtonRedPng);
index.startBattleButton = images.fromBase64(startBattleButtonPng);
index.supportSelectButton = images.fromBase64(supportSelectButtonPng);
index.supportSkillAvailable = images.fromBase64(supportSkillAvailablePng);
index.tapButton = images.fromBase64(tapButtonPng);
index.transformGaugeFull = images.fromBase64(transformGaugeFullPng);
